Fix/public ip arg build ipv6
teonet-co/teonet pull request #143
Opened 2020-09-29 13:50 UTC by kshokhin

2020-09-29 15:14 UTC, chernikovdmitry requested changes
Looks like it would leak memory

2020-09-29 15:14 UTC, chernikovdmitry commented on app/teovpnstarter.c
> +        "http://169.254.169.254/latest/meta-data/network/interfaces/macs/%sipv6s", buffer);
Config?
```suggestion
    snprintf(ipv6_url_request_buffer, ipv6_url_buffer_size, 
        "%s%sipv6s", ipv6_request_url, buffer);
```

2020-09-29 15:14 UTC, chernikovdmitry commented on app/teovpnstarter.c
> +    const char* ipv6_url_pattern = "http://169.254.169.254/latest/meta-data/network/interfaces/macs/ipv6s";
Config?

2020-09-29 15:14 UTC, chernikovdmitry commented on app/teovpnstarter.c
> +        settings->public_ipv6 = strdup(buffer);
same, no need in strdup

2020-10-12 13:24 UTC, angelskieglazki approved these changes

2020-10-12 13:24 UTC, angelskieglazki commented on app/teovpnstarter.c
> +            buffer->data = (char*)realloc(buffer->data, buffer->capacity);
ccl_realloc can use

2020-10-12 13:44 UTC, chernikovdmitry requested changes

2020-10-12 13:44 UTC, chernikovdmitry commented on app/teovpnstarter.c
> +}
```suggestion
void set_buffer(Buffer *buffer, const char* data, size_t data_size) {
    if (buffer == NULL) { return; }

    free(buffer->data);

    if (data == NULL || data_size == 0) {
      buffer->data = NULL;
      buffer->capacity = 0;
      buffer->size = 0;
      return;
    }

    buffer->data = (char*)malloc(data_size);
    memcpy(buffer->data, data, data_size);
    buffer->size = data_size;
    buffer->capacity = data_size;
}
```

2020-10-12 13:44 UTC, chernikovdmitry commented on app/teovpnstarter.c
>      CURLcode res = curl_easy_perform(curl);
At lines 105-108 should be
```
    if (res != CURLE_OK) {
        printf("request_public_ipv4 failed: %s\n", curl_easy_strerror(res));
        destroy_buffer(&data_buffer);
        return 0;
    }
```

2020-10-12 13:44 UTC, chernikovdmitry commented on app/teovpnstarter.c
>      CURLcode res = curl_easy_perform(curl);
Same, destroy_buffer(&data_buffer); if (res != CURLE_OK)

2020-10-12 13:44 UTC, chernikovdmitry commented on app/teovpnstarter.c
>      if (res != CURLE_OK) {
destroy_buffer(&data_buffer);

2020-10-14 14:58 UTC, chernikovdmitry approved these changes
Cool story :cool:

2020-10-14 14:59 UTC, merged